"""sync models

Revision ID: 523665eb5747
Revises: 81294d2d61f2
Create Date: 2025-08-19 10:00:27.890246
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "523665eb5747"
down_revision = "81294d2d61f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
