"""sync models

Revision ID: 81294d2d61f2
Revises: 57f91720e2e2
Create Date: 2025-08-19 10:00:13.852967
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "81294d2d61f2"
down_revision = "57f91720e2e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
